import SwiftUI

struct ChatTab: View {
    @EnvironmentObject private var store: SocialStore
    var body: some View { NavigationStack { List { Section { ForEach(store.chats) { chat in NavigationLink { ConversationView(name: chat.name) } label: { HStack(spacing: 12) { Circle().fill(.blue.opacity(0.15)).frame(width: 48, height: 48).overlay(Text(chat.name.prefix(1)).bold().foregroundColor(.blue)); VStack(alignment: .leading, spacing: 4) { Text(chat.name).font(.headline); Text(chat.message).font(.caption).foregroundColor(.secondary).lineLimit(1) }; Spacer(); VStack(alignment: .trailing, spacing: 5) { Text(chat.time).font(.caption2).foregroundColor(.secondary); if chat.unread > 0 { Text("\(chat.unread)").font(.caption2.bold()).foregroundColor(.white).padding(5).background(.orange).clipShape(Circle()) } } } } } } }.listStyle(.insetGrouped).navigationTitle("聊天").toolbar { ToolbarItem(placement: .topBarTrailing) { Image(systemName: "square.and.pencil") } } } }
}
struct ConversationView: View { let name: String; @State private var text = ""; @State private var messages = ["你好，很高兴认识你！", "最近在忙什么？"]
    var body: some View { VStack { ScrollView { VStack(alignment: .leading, spacing: 12) { ForEach(messages, id: \.self) { Text($0).padding(11).background(.white).clipShape(RoundedRectangle(cornerRadius: 14)) } }.frame(maxWidth: .infinity, alignment: .leading).padding() }; HStack { TextField("输入消息", text: $text).textFieldStyle(.roundedBorder); Button { if !text.isEmpty { messages.append(text); text = "" } } label: { Image(systemName: "arrow.up.circle.fill").font(.title) }.foregroundColor(.orange) }.padding() }.background(Color(.systemGroupedBackground)).navigationTitle(name).navigationBarTitleDisplayMode(.inline) }
}
struct MeTab: View { var body: some View { NavigationStack { List { Section { HStack(spacing: 14) { Circle().fill(.orange.opacity(0.2)).frame(width: 70, height: 70).overlay(Text("我").font(.title.bold()).foregroundColor(.orange)); VStack(alignment: .leading) { Text("林檎").font(.title2.bold()); Text("@troll_user").foregroundColor(.secondary); Text("分享生活，保持好奇").font(.caption).foregroundColor(.secondary) } } }.listRowBackground(Color.clear); Section { NavigationLink("我的动态", destination: Text("我的动态")); NavigationLink("收藏", destination: Text("我的收藏")); NavigationLink("获赞与互动", destination: Text("获赞与互动")) }; Section { NavigationLink("账号与隐私", destination: Text("账号与隐私")); NavigationLink("通知设置", destination: Text("通知设置")); NavigationLink("关于 TrollSocial", destination: Text("关于 TrollSocial")) } }.scrollContentBackground(.hidden).background(Color(.systemGroupedBackground)).navigationTitle("我的") } }
}
struct ComposerView: View { @EnvironmentObject private var store: SocialStore; @Environment(\.dismiss) private var dismiss; @State private var text = ""
    var body: some View { NavigationStack { VStack(alignment: .leading, spacing: 16) { TextEditor(text: $text).frame(minHeight: 180).padding(8).background(Color(.systemGroupedBackground)).clipShape(RoundedRectangle(cornerRadius: 12)); HStack { Label("公开", systemImage: "globe"); Spacer(); Text("\(text.count)/500").foregroundColor(.secondary) }; Spacer() }.padding().navigationTitle("发布动态").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .topBarLeading) { Button("取消") { dismiss() } }; ToolbarItem(placement: .topBarTrailing) { Button("发布") { store.publish(text) }.bold().disabled(text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty) } } } }
}
